# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MammothTag' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MammothTag
  
  pod 'Alamofire'
  pod 'CountryPickerView', '~> 3.2.0'


  target 'MammothTagTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MammothTagUITests' do
    # Pods for testing
  end

end
